### PR TITLE
Added an option to run a batch file as an alarm

### PR DESCRIPTION
**Pull request by BoxOfSnoo**
I am totally new to Python but I wanted to run this on my headless (and soundless) Linux box.  I created a batch file that will push an iOS notification to my phone (and my Pebble) whenever the game updates.

I am sure there are tweaks that can be done to this but it runs.

### CODE REVIEW

**Comment by Magnitus-** [comment]
I like the idea of adding shell script support for those who are so inclined. However, I would like the script's name to have a more generic name (maybe AlarmScript.sh).

Also, it probably shouldn't be the default setting, because I think the majority of users aren't the type to do shell scripts.

Maybe something like checking for the existence of "AlarmScript.sh" (hint: os.path.exists) and if it exists, execute the script to handle the alarm, else fallback on current behavior.

**Comment by BoxOfSnoo** [comment]
I got it working again, with the cleanups you added later.  I removed the stock level stuff because it used to be simpler to locate in the script, now it's in too many places for me to figure out and maintain.  

The problem is that every time the stock drops by one it detects that it's a new game, because the whole game info object bundles together all of the info about the game, and doesn't just compare the titles.  Maybe someone more familiar with the language can get it going but I had to experiment to figure out just how to use an and in a condition...

Do I need to create a new pull request for the current commit, if you want my changes?  Or can you choose the HEAD of this repo?

**Comment by Magnitus-** [comment]
I don't think you need to perform another pull.

The batch file handling seems good. I'll need to check the other changes you mentioned before I merge thought. I have to leave for a couple of hours, but I'll check later tonight.

Thanks for your contribution.

**Comment by Magnitus-** [comment]
Ok, Sorry for the delay. I reviewed your the changes in your 2 commits.

The first one is definitely an improvement.  In the second commit: the checking that the file exists is an improvement.

The rest of the changes are more nebulous. First of all, when checking for new games, the master branch does compare titles only. self._getCurrentGames is used, which fetches only the titles in a list after which they are compared to previous titles using set operators (I coded that bit myself).

I agree that the whole verbose bit that you removed (along with the  _getCurrentStock function) in the _pollServer function needs to be restructured: probably a good candidate to only execute if VERBAL is True, plus it would need to be abstracted away in an outside call so that _pollServer can be kept general and not specific to a particular promo.

However, I don't think it should be removed as I think many users will appreciate the detailed feedback. If you could introduce that part of the code back (I'll restructure it afterwards), I think your changes will be good for merging.

**Comment by BoxOfSnoo** [comment]
I added it back in.  It insisted on firing every stock change until I removed that information from **repr**.  I don't understand enough Python to know why.

**Comment by Magnitus-** [comment]
GameInfo from the master doesn't take stocks and the script doesn't print them. I should have clued in about that when I looked at your previous diffs and when you told me about new game alerts being triggered with changing stocks. 

I'm unsure how that could have occurred if you worked with a fresh copy from the master prior to your last 3 commits, but I'm far from an expert on Git branching and merging.  Maybe you'd find it easier to re-implement your bash script support from a fresh master copy and see if that works as intended rather than try to make your current script fit the master branch, minus your bash script support.

**Comment by BoxOfSnoo** [comment]
I did merge from master recently. My original pull request was with an old version, before it was restructured.  I added the stock printing, so GameInfo now takes stocks with my addition... I tried to add it across the board but when I had it in **repr** also it must have interfered with the comparator function.

I tried to add the ability to pass the game title to the script as a parameter but couldn't figure out how to cleanly get the title or quote it safely.  Promo's almost over anyway...

**Comment by Magnitus-** [comment]
Well, I intend to use updated versions of this script for future insomnia promos.

My initial assumption was that all your previous 3 commits were from a fresh master copy, but I now realize that it was from a merge between between the master and your previous modifications. I'll try to ascertain the full extent of the modifications of your final version with regard to the master branch.

**Pull request merged**
